In [11]:
# Question 1:

import numpy as np
ar=np.arange(12)
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
x=ar.reshape(3,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
x.ndim

2

In [15]:
# question2
ar=np.array([7,5,9])
a=np.repeat(ar,3)
print(a)

[7 7 7 5 5 5 9 9 9]


In [17]:
# Question 3
ar1=np.array([1,2,3,4,5])
ar2=np.array([4,5,6,7,8])
a=np.intersect1d(ar1,ar2)

In [18]:
print(a)

[4 5]


In [19]:
ar1=np.array([1,2,3,4,5])
ar2=np.array([4,5,6,7,8])
a=np.union1d(ar1,ar2)

In [20]:
print(a)

[1 2 3 4 5 6 7 8]


In [22]:
# question 4
ar1=np.array([1,2,3,4,5])
ar2=np.array([4,5,6,7,8])
a=np.setdiff1d(ar1,ar2)

In [23]:
print(a)

[1 2 3]


In [24]:
# Question 5
ar1=np.array([1,2,3,4,5])
ar2=np.array([1,5,6,4,8])
a=np.where(ar1==ar2)


In [25]:
print(a)

(array([0, 3], dtype=int64),)


In [26]:
# Question 5
ar1=np.array([1,2,3,4,5])
ar2=np.array([1,5,6,4,8])
a=np.where(ar1!=ar2)


In [27]:
print(a)

(array([1, 2, 4], dtype=int64),)


In [39]:
a=np.random.randint(5,10)
for i in range(5,10):
      print(i, end=" ")

5 6 7 8 9 

In [40]:
# Question 6
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
index=np.where((a>=5)&(a<=10))
a[index]

array([5, 6, 7, 8, 9])